[project]
name = "llm-connector"
version = "0.1.0"
description = ""
readme = "src/llm_connector/README.md"
requires-python = ">=3.12"
dependencies = []



[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/llm_connector"]


