[project]
name = "tree-filler"
version = "0.1.0"
description = ""
readme = "src/tree_filler/README.md"
requires-python = ">=3.12"
dependencies = []


[project.scripts]
fill-tree = "tree_filler.fill_tree:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tree_filler"]


