[project]
name = "tool"
version = "0.1.0"
description = ""
readme = "src/tool/README.md"
requires-python = ">=3.12"
dependencies = [
    "db-connector",
    "llm-connector",
    "tree-builder",
    "tree-filler",
    "utils",
    "argparse"

]

[project.scripts]
run-tool-cli =  "tool.cli:start_cli"



[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tool"]
